#include <stdio.h>  
#include "time.h"      /* time.h generated by rpcgen */   

int main(int argc, char **argv)  
{  
    CLIENT *clnt;  
    char *result;  
    char *server;  
    char *message;   
  
    if (argc != 3) {  
        fprintf(stderr, "usage: %s host message", argv[0]);  
        return -1;  
    }

    server = argv[1];  
    message = argv[2];  

    clnt = clnt_create(server, TIMEPROG, PRINTTIMEVERS, "TCP");   
    if (clnt == NULL) {   
        clnt_pcreateerror(server);  
        return -1;  
    }  

    result = *printtime_1(&message, clnt);  
    if (result== (char *)NULL) {  
        clnt_perror(clnt, server);  
        return -1;  
    }  

    if (strcmp(result,"Error")==0){  
        fprintf(stderr, "%s: could not get the time",argv[0]);  
        return -1;  
    }  

    printf("From the Time Server : %s",result);    
    clnt_destroy( clnt );  
    return 0;
}

